# Generated by Django 5.0.4 on 2024-07-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Contact', 'Contact'), ('Article', 'Article'), ('Book', 'Book'), ('Quote', 'Quote'), ('Equation', 'Equation'), ('Code', 'Code'), ('Project', 'Project'), ('Task', 'Task')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('related to', 'Related to'), ('cited by', 'Cited by'), ('part of', 'Part of')], max_length=50)),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_item1', to='interface.item')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_item2', to='interface.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.item')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tag')),
            ],
            options={
                'unique_together': {('item', 'tag')},
            },
        ),
    ]
