# Generated by Django 5.0.4 on 2024-07-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_item_tag_relationship_itemtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Contact', 'Contact'), ('Article', 'Article'), ('Book', 'Book'), ('Quote', 'Quote'), ('Equation', 'Equation'), ('Code', 'Code'), ('Project', 'Project'), ('Task', 'Task'), ('Presentation', 'Presentation'), ('Research Paper', 'Research Paper'), ('Journal Entry', 'Journal Entry'), ('Report', 'Report'), ('Manual', 'Manual'), ('Guide', 'Guide'), ('Diagram', 'Diagram'), ('Image', 'Image'), ('Video', 'Video'), ('Audio', 'Audio'), ('Spreadsheet', 'Spreadsheet'), ('Dataset', 'Dataset'), ('Note', 'Note'), ('Email', 'Email'), ('Letter', 'Letter'), ('Survey', 'Survey'), ('Form', 'Form'), ('Resume', 'Resume'), ('Cover Letter', 'Cover Letter'), ('Policy Document', 'Policy Document'), ('Procedure', 'Procedure'), ('Contract', 'Contract'), ('Invoice', 'Invoice'), ('Receipt', 'Receipt'), ('Meeting Minutes', 'Meeting Minutes'), ('Agenda', 'Agenda'), ('Newsletter', 'Newsletter'), ('Brochure', 'Brochure'), ('Flyer', 'Flyer'), ('Press Release', 'Press Release'), ('Announcement', 'Announcement'), ('Memo', 'Memo'), ('White Paper', 'White Paper'), ('Case Study', 'Case Study'), ('Technical Specification', 'Technical Specification'), ('Blueprint', 'Blueprint'), ('Map', 'Map'), ('Flowchart', 'Flowchart'), ('Storyboard', 'Storyboard'), ('Mind Map', 'Mind Map'), ('Checklist', 'Checklist'), ('To-Do List', 'To-Do List'), ('Calendar Event', 'Calendar Event'), ('Log', 'Log'), ('Schedule', 'Schedule'), ('Plan', 'Plan'), ('Strategy', 'Strategy'), ('Proposal', 'Proposal'), ('Quote (Sales)', 'Quote (Sales)'), ('Order', 'Order'), ('Shipping Document', 'Shipping Document'), ('Warranty', 'Warranty'), ('User Feedback', 'User Feedback'), ('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request'), ('Interview', 'Interview'), ('Transcript', 'Transcript'), ('Speech', 'Speech'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Review', 'Review'), ('Critique', 'Critique'), ('Opinion', 'Opinion'), ('Editorial', 'Editorial'), ('Recipe', 'Recipe'), ('Menu', 'Menu'), ('Blog Post', 'Blog Post'), ('Web Page', 'Web Page'), ('Forum Post', 'Forum Post'), ('Social Media Post', 'Social Media Post'), ('Message', 'Message'), ('Comment', 'Comment'), ('Forum Thread', 'Forum Thread'), ('Webinar', 'Webinar'), ('Online Course', 'Online Course'), ('Training Material', 'Training Material'), ('Certification', 'Certification'), ('License', 'License'), ('Patents', 'Patents'), ('Trademark', 'Trademark'), ('Copyright', 'Copyright'), ('Legal Document', 'Legal Document'), ('Regulation', 'Regulation'), ('Standard', 'Standard'), ('Code of Conduct', 'Code of Conduct'), ('Guideline', 'Guideline'), ('FAQ', 'FAQ'), ('Help Document', 'Help Document'), ('Support Ticket', 'Support Ticket'), ('Troubleshooting Guide', 'Troubleshooting Guide')], max_length=50),
        ),
    ]
