# Generated by Django 5.0.4 on 2024-07-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
