# Generated by Django 5.0.4 on 2024-07-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_item_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
