# Generated by Django 5.0.4 on 2024-07-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_area_aspect_branch_domain_field_section_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.domain'),
        ),
    ]
