# Generated by Django 5.0.4 on 2024-10-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_item_last_time_item_next_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
