# Generated by Django 5.0.4 on 2024-10-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, default='Mody', max_length=255, null=True),
        ),
    ]
