# Generated by Django 5.0.4 on 2024-10-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_platform_item_fplatform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='author_name',
            new_name='platform_name',
        ),
    ]
