# Generated by Django 5.1.3 on 2025-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_item_init_time_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hide_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
