# Generated by Django 5.1.3 on 2025-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_item_hide_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
